### ISSUE TITLE
problem with the tool-bar (complie to cloud does not exist)

### ISSUE THREAD

**Issue by savra0923** [robotican/krembot_1.0#2]
Hi all,

I've been using particle-dev on atom IDE for a while now with my Krembot robots.
A little while ago, there was an update for the tool-bar package (which is a dependency particle-dev-libraries uses). The update deleted all the icons I was using to debug, compile, and flush onto the robots (I can't even choose a single robot to flush on it) and I have no idea how to get them back (Infect I'm not sure if I should be asking you or the particle-dev guys).

Not only that, the "particle" tab at the top left of the screen does not respond.

Do you guy have any suggestion?

**Comment by elhayra** [comment]
Hi, 

Particle's IDE have some bugs, but I didn't encounter the one you mentioned.
I suggest you try to delete the IDE completely and try to reinstall.
I am closing this issue because it is not Krembot related, but a Particle one. You should contact them for more help.
